
title = "Tradable Securities Contract Specifications"

[securities]
  [securities.TPCF]
    ticker = 'TPCF'
    lot = 4
    decimals = 2
    settlement = 'cash'
    max_price = 99999
    min_price = 1
    can_trade = true
  [securities.TPCF.arguments]
    [securities.TPCF.arguments.buy_turn]
      name = "buy_turn"
      size = 2
      values = ['01', '02', '03', '04', '05', '06', '07', '08', '09', '10']
    [securities.TPCF.arguments.sell_turn]
      name = "sell_turn"
      size = 2
      values = ['01', '02', '03', '04', '05', '06', '07', '08', '09', '10']

  # [securities.TPCO] # Maybe one for each turn option? idk how to encode this
  #   ticker = 'TPCO'
  #   lot = 100
  #   decimals = 2
  #   multiplier = 100
  #   settlement = 'cash'
  #   max_price = 99999
  #   min_price = 1
  #   option_type = 'european'
  #   can_trade = false
  # [securities.TPCO.arguments]
  #   [securities.TPCO.arguments.expiry]
  #     name = "expiry"
  #     size = 2
  #     values = ['01', '02', '03', '04', '05', '06', '07', '08', '09', '10']
  #   [securities.TPCO.arguments.call_put]
  #     name = "call_put"
  #     size = 1
  #     values = ['C','P']
  #   [securities.TPCO.arguments.strike]
  #     name = "strike"
  #     size = 3
  #     values = ['001', '002', '003', '004', '005', '006', '007', '008', '009', '010', '011', '012', '013', '014', '015', '016', '017', '018', '019', '020', '021', '022', '023', '024', '025', '026', '027', '028', '029', '030', '031', '032', '033', '034', '035', '036', '037', '038', '039', '040', '041', '042', '043', '044', '045', '046', '047', '048', '049', '050', '051', '052', '053', '054', '055', '056', '057', '058', '059', '060', '061', '062', '063', '064', '065', '066', '067', '068', '069', '070', '071', '072', '073', '074', '075', '076', '077', '078', '079', '080', '081', '082', '083', '084', '085', '086', '087', '088', '089', '090', '091', '092', '093', '094', '095', '096', '097', '098', '099', '100', '101', '102', '103', '104', '105', '106', '107', '108', '109', '110', '111', '112', '113', '114', '115', '116', '117', '118', '119', '120', '121', '122']

